imx-media-objs := imx-media-dev.o imx-media-of.o
imx-ic-objs := imx-ic-common.o imx-ic-prpenc.o imx-ic-prpvf.o imx-ic-pp.o

obj-$(CONFIG_VIDEO_IMX_MEDIA) += imx-media.o
obj-$(CONFIG_VIDEO_IMX_MEDIA) += imx-media-common.o
obj-$(CONFIG_VIDEO_IMX_MEDIA) += imx-ic.o

obj-$(CONFIG_VIDEO_IMX_CAMERA) += imx-camif.o
obj-$(CONFIG_VIDEO_IMX_CAMERA) += imx-csi.o
obj-$(CONFIG_VIDEO_IMX_CAMERA) += imx-smfc.o
obj-$(CONFIG_IMX_MIPI_CSI2) += imx-mipi-csi2.o
obj-$(CONFIG_IMX_VIDEO_SWITCH) += imx-video-switch.o
obj-$(CONFIG_IMX_OV5640_MIPI) += ov5640-mipi.o
obj-$(CONFIG_IMX_OV5642) += ov5642.o

obj-$(CONFIG_VIDEO_IMX_M2M) += imx-m2m.o
